### ISSUE TITLE
Flags on CMOC/Mii Contest

### ISSUE THREAD

**Issue by Matejono** [RiiConnect24/CMOC-Server#2]
Hey, I noticed that some people, who set up their countries which weren´t supported before (Poland, Romania, Russia) don´t show their flag. They are shown with just question mark. Would be possible to add those flags there?
![DSC_002731](https://user-images.githubusercontent.com/78499885/106790516-f72a5f00-6653-11eb-95b9-ca5579e1d8d2.jpg)

**Comment by KcrPL** [comment]
Unfortunately, I don't think this is possible server side. Client side is out of our scope.

**Comment by Matejono** [comment]
Okay then, thanks anyway
